listenAddr: ":8080"
logLevel: "debug"

neoRPC: "http://localhost:20332"
walletPath: "/app/wallets/dev.wallet.json"
walletPass: "dev-pass"

nftContractHash: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
marketContractHash: "cccccccccccccccccccccccccccccccccccccccc"
tokenContractHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
